### PR TITLE
fix: remediate review findings + failing `test` CI on #360

### PR DESCRIPTION
**Pull request by groupthinking**
Stacked on top of #360 (`copilot/fix-performance-issues`). Merging this branch into #360's branch clears the three open review threads and the failing `test` job.

## What this fixes

**1. `_build_chunks()` infinite loop / negative slice** — `src/youtube_extension/backend/api/v1/router.py`
A sentence/word boundary found close to `start` made `start = end - overlap` stall or move backwards (infinite loop / negative slicing). Now we only snap to a boundary that leaves the chunk longer than the overlap, and `start` advances by at least one char every iteration. Verified against pathological inputs (boundary at offset 0, all-periods, no-boundary, boundary just past the overlap) — terminates cleanly in every case.

**2. `Promise.race()` hangs when all candidates resolve null** — `apps/web/src/lib/transcription-service.ts`
`p.then(r => r ?? PENDING_FOREVER)` produced a never-settling race when every candidate returned null, so the function never reached Strategy 4. Replaced with `firstNonNull()`, which resolves on the first usable transcript or `null` once all candidates have settled.

**3. `test_list_videos_pagination` failure (the failing `test` CI job)** — `tests/unit/test_v1_router_extended.py`
The router now delegates pagination to `DataService.get_videos_summary`, so the `MagicMock` must honor `limit`/`offset`. Switched the mock from a static `return_value` to a `side_effect` that slices (`offset` beyond total → empty page).

**4. Flaky mtime ordering** — `tests/unit/test_data_service.py`
`test_pagination_offset` created files in a tight loop that can share an mtime at filesystem resolution. Now spaces mtimes with `os.utime` so newest-first ordering is deterministic.

## Not addressed here
The `build` job fails on `Cannot find module '@opentelemetry/instrumentation'` (loaded via `@sentry/nextjs` in `next.config.js`). This PR touches none of `next.config.js`, `package.json`, or Sentry — it's a pre-existing dependency-resolution issue, not a regression from #360. Flagging for a separate dependency fix.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01X461xhciwcK5s5fm1protx

---
_Generated by [Claude Code](https://claude.ai/code/session_01X461xhciwcK5s5fm1protx)_

### CODE REVIEW

**Comment by groupthinking** [comment]
## Remediation status

This branch is stacked on `copilot/fix-performance-issues` (#360). The single commit here clears the three open review threads on #360 and the failing **`test`** CI job:

- **`_build_chunks()` loop/negative-slice guard** — boundary snapping is now only applied when it leaves a chunk longer than the overlap, and `start` advances ≥1 char/iteration (verified against pathological inputs: boundary at offset 0, all-periods, no-boundary, boundary just past the overlap).
- **`Promise.race()` null-hang** — replaced `PENDING_FOREVER` with `firstNonNull()`, which always settles (first usable transcript, or `null` once all candidates settle) so the function falls through to Strategy 4 instead of hanging.
- **`test_list_videos_pagination`** — the mock `get_videos_summary` now honors `limit`/`offset` (the router delegates pagination to the service).
- **Flaky mtime ordering** — `test_pagination_offset` now spaces mtimes via `os.utime`.

### ⚠️ The `Vercel` / `build` red here is pre-existing and NOT from this PR
Both fail with `Cannot find module '@opentelemetry/instrumentation'` while *loading `next.config.js`* (via `withSentryConfig` → `@sentry/nextjs@^10.57.0` → `@sentry/node-core`). This happens **before any source is compiled**, reproduces identically on #360 and on `main`, and is independent of this diff. It's a missing transitive dependency, not a code regression.

Fixing it is a version-sensitive change to a shared `package.json` (pick an `@opentelemetry/instrumentation` version compatible with the installed `@sentry/*` / `@opentelemetry/*` set) and affects the whole repo — so I've **deliberately left it out of this remediation** rather than bundle an unrelated dependency bump. Happy to open a separate PR for it on request.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by groupthinking** [comment]
@coderabbitai review

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by groupthinking** [comment]
Closing: has merge conflicts and is superseded by newer fixes on main. Will be re-addressed in the hybrid refactor branch.
