### PR TITLE
fix(unified-ai-sdk): restore CLAUDE/GROK ModelProvider members broken by #773 (main is red)

### PR DESCRIPTION
**Pull request by groupthinking**
## What & why

`main` is currently **red** — the CI `test` job has failed on every push since **#773** ("consolidate…", `3c73eeb`), and the failure cascaded to #766 (`784ed3a`) and #763 (`c491730`, current HEAD).

Root cause is a **production runtime regression**, not just test drift. #773 trimmed the `ModelProvider` enum in `src/unified_ai_sdk/rate_limiter.py` to `{OPENAI, ANTHROPIC, GEMINI}`, dropping `CLAUDE` and `GROK` — but left every consumer in `unified_ai_sdk.py` still referencing them by name:

```python
# UnifiedAISDK._rate_limit_provider() — runs on every request
if provider_name == "claude":
    return ModelProvider.CLAUDE   # AttributeError: no attribute 'CLAUDE'
...
if provider_name == "grok":
    return ModelProvider.GROK     # AttributeError: no attribute 'GROK'
```

So **every Anthropic (Claude) and Grok inference call now raises** `AttributeError: type object 'ModelProvider' has no attribute 'CLAUDE'` / `'GROK'` inside `unified_request`. The handler dict, `_normalize_provider`, `health_check`, and Grok client init were all left intact — only the enum definition changed — so #773's consolidation was **incomplete**, not a deliberate removal.

The failing tests correctly caught it:

```
FAILED tests/unit/test_unified_ai_sdk.py::test_unified_request_uses_anthropic_client - AttributeError: type object 'ModelProvider' has no attribute 'CLAUDE'
FAILED tests/unit/test_unified_ai_sdk.py::test_unified_request_uses_grok_client      - AttributeError: type object 'ModelProvider' has no attribute 'GROK'
```

## Change

Restore `CLAUDE = "claude"` and `GROK = "grok"` to the enum (keeping `ANTHROPIC = "anthropic"`, which `_normalize_provider` already resolves to the `"claude"` path). Adding enum members is **purely additive** and cannot break existing importers. A docstring documents the coupling so the members aren't dropped again without updating `unified_ai_sdk.py`.

```diff
 class ModelProvider(Enum):
     OPENAI = "openai"
+    CLAUDE = "claude"
     ANTHROPIC = "anthropic"
     GEMINI = "gemini"
+    GROK = "grok"
```

## Verification

```
$ python -m pytest tests/unit/test_unified_ai_sdk.py -q
14 passed
```

(Previously 2 failed.) Runtime dispatch (`_rate_limit_provider("claude")`, `("grok")`, `_normalize_provider(ModelProvider.ANTHROPIC)`) all resolve without raising.

## Scope

One file (`src/unified_ai_sdk/rate_limiter.py`), additive enum change plus a docstring. Branched fresh from current `main` (`c491730`).

## Open question for maintainer

This restores the pre-#773 working behaviour. If #773 *intended* to standardise on `ANTHROPIC` and drop Grok support entirely, the correct follow-up is the opposite direction — remove the `claude`/`grok` handlers, normalization aliases, `health_check` entries, Grok client init, and the two tests — which is a larger, product-level decision. This PR deliberately takes the minimal, reversible path to get `main` green and unbreak Claude/Grok in production **now**; the consolidation can be redone completely as a separate change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---
_Generated by [Claude Code](https://claude.ai/code/session_017p5FY1c2iETUWdDVDfyeJj)_

### CODE REVIEW

**Comment by groupthinking** [comment]
@coderabbitai review

Context for reviewers: this is a minimal, additive fix restoring the `CLAUDE` and `GROK` members to `ModelProvider`, which #773 removed while leaving `UnifiedAISDK._rate_limit_provider()` still referencing them by name — a runtime `AttributeError` on every Claude/Grok request and a red `test` job on `main`. Adding enum members is backward-compatible. `tests/unit/test_unified_ai_sdk.py` now passes 14/14 (was 2 failed). See the PR description for the open question on whether #773 intended to drop Grok entirely.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by groupthinking** [comment]
@coderabbitai review

Please re-evaluate against the latest commit (`f0520d0`), which addresses the two pre-merge warnings from the prior run:
- **Require AI Unit Tests**: added `TestModelProviderContract` in `tests/unit/test_unified_ai_sdk.py` — three regression tests that lock the `ModelProvider` enum to its consumers so the #773 failure mode (Claude/Grok `AttributeError` in `_rate_limit_provider`) fails fast in unit tests. The `copilot-rabbit` label is now applied. Full file: 17 passed locally.
- **Enforce Copilot Verification**: a GitHub Copilot review has been requested on this PR.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by groupthinking** [comment]
Thanks @devin-ai-integration — all three findings are accurate, and (as each notes) **none has runtime impact**. Confirmed against the tree:

1. **Dead `"anthropic"` stats key in `bridge.py:96`** — the `by_provider` dict is init-only (single occurrence, never written), so the extra key is inert.
2. **`list(ModelProvider)` double-entry in the `model_router` fallback** — only reached if the configured fallback yields zero valid providers; would harmlessly retry the same provider.
3. **Separate `wait_if_needed` buckets for `ANTHROPIC` vs `CLAUDE`** — unreachable today: `unified_request` always routes through `_rate_limit_provider`, which returns `ModelProvider.CLAUDE`. `ModelProvider.ANTHROPIC` isn't referenced by name anywhere in production (only in the alias-mapping unit test).

All three trace to one intentional choice in this PR: keeping **both** `CLAUDE` and `ANTHROPIC` as members. This PR is a **minimal regression fix** — it restores the members `_rate_limit_provider` hard-references so the red `test` job goes green, and keeps `ANTHROPIC` so any caller that adopted #773's `"anthropic"` spelling doesn't break.

Whether to **collapse to one member per provider** (drop `ANTHROPIC`, or the reverse — standardize on `ANTHROPIC` and drop `CLAUDE`/`GROK`, fully completing #773's consolidation) is the open product decision already called out in the PR description. It's deliberately deferred to a separate, maintainer-owned change rather than expanded here, so this fix stays surgical. Leaving these threads open for that follow-up rather than resolving them.

---
_Generated by [Claude Code](https://claude.ai/code)_
